// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connect.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeliverMessageReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Message              *Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeliverMessageReq) Reset()         { *m = DeliverMessageReq{} }
func (m *DeliverMessageReq) String() string { return proto.CompactTextString(m) }
func (*DeliverMessageReq) ProtoMessage()    {}
func (*DeliverMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{0}
}

func (m *DeliverMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliverMessageReq.Unmarshal(m, b)
}
func (m *DeliverMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliverMessageReq.Marshal(b, m, deterministic)
}
func (m *DeliverMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliverMessageReq.Merge(m, src)
}
func (m *DeliverMessageReq) XXX_Size() int {
	return xxx_messageInfo_DeliverMessageReq.Size(m)
}
func (m *DeliverMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliverMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeliverMessageReq proto.InternalMessageInfo

func (m *DeliverMessageReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeliverMessageReq) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type DeliverMessageResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeliverMessageResp) Reset()         { *m = DeliverMessageResp{} }
func (m *DeliverMessageResp) String() string { return proto.CompactTextString(m) }
func (*DeliverMessageResp) ProtoMessage()    {}
func (*DeliverMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{1}
}

func (m *DeliverMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliverMessageResp.Unmarshal(m, b)
}
func (m *DeliverMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliverMessageResp.Marshal(b, m, deterministic)
}
func (m *DeliverMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliverMessageResp.Merge(m, src)
}
func (m *DeliverMessageResp) XXX_Size() int {
	return xxx_messageInfo_DeliverMessageResp.Size(m)
}
func (m *DeliverMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliverMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeliverMessageResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DeliverMessageReq)(nil), "pb.DeliverMessageReq")
	proto.RegisterType((*DeliverMessageResp)(nil), "pb.DeliverMessageResp")
}

func init() {
	proto.RegisterFile("connect.proto", fileDescriptor_778b7e3040344da6)
}

var fileDescriptor_778b7e3040344da6 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0xcb,
	0x4b, 0x4d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x92, 0xe2, 0xcd,
	0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x85, 0x08, 0x29, 0x79, 0x71, 0x09, 0xba, 0xa4, 0xe6, 0x64,
	0x96, 0xa5, 0x16, 0xf9, 0x42, 0xc4, 0x83, 0x52, 0x0b, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0x98, 0x32, 0x53, 0x84, 0x54, 0xb9, 0xd8, 0xa1, 0xba, 0x24,
	0x98, 0x14, 0x18, 0x35, 0xb8, 0x8d, 0xb8, 0xf5, 0x0a, 0x92, 0xf4, 0x60, 0x1a, 0x60, 0x72, 0x4a,
	0x22, 0x5c, 0x42, 0xe8, 0x66, 0x15, 0x17, 0x18, 0x79, 0x73, 0x71, 0x38, 0xe7, 0xe7, 0xe5, 0x79,
	0xe6, 0x65, 0x96, 0x08, 0xd9, 0x73, 0xf1, 0xa1, 0xaa, 0x10, 0x12, 0x05, 0x99, 0x84, 0xe1, 0x02,
	0x29, 0x31, 0x6c, 0xc2, 0xc5, 0x05, 0x49, 0x6c, 0x60, 0x57, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x75, 0x88, 0x31, 0xab, 0xd9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ConnInitClient is the client API for ConnInit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConnInitClient interface {
	DeliverMessage(ctx context.Context, in *DeliverMessageReq, opts ...grpc.CallOption) (*DeliverMessageResp, error)
}

type connInitClient struct {
	cc grpc.ClientConnInterface
}

func NewConnInitClient(cc grpc.ClientConnInterface) ConnInitClient {
	return &connInitClient{cc}
}

func (c *connInitClient) DeliverMessage(ctx context.Context, in *DeliverMessageReq, opts ...grpc.CallOption) (*DeliverMessageResp, error) {
	out := new(DeliverMessageResp)
	err := c.cc.Invoke(ctx, "/pb.ConnInit/DeliverMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnInitServer is the server API for ConnInit service.
type ConnInitServer interface {
	DeliverMessage(context.Context, *DeliverMessageReq) (*DeliverMessageResp, error)
}

// UnimplementedConnInitServer can be embedded to have forward compatible implementations.
type UnimplementedConnInitServer struct {
}

func (*UnimplementedConnInitServer) DeliverMessage(ctx context.Context, req *DeliverMessageReq) (*DeliverMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliverMessage not implemented")
}

func RegisterConnInitServer(s *grpc.Server, srv ConnInitServer) {
	s.RegisterService(&_ConnInit_serviceDesc, srv)
}

func _ConnInit_DeliverMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnInitServer).DeliverMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ConnInit/DeliverMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnInitServer).DeliverMessage(ctx, req.(*DeliverMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConnInit_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ConnInit",
	HandlerType: (*ConnInitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeliverMessage",
			Handler:    _ConnInit_DeliverMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connect.proto",
}
