// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SessionType int32

const (
	SessionType_Unknown       SessionType = 0
	SessionType_SignIn        SessionType = 1
	SessionType_Sync          SessionType = 2
	SessionType_Heartbeat     SessionType = 3
	SessionType_MessageStream SessionType = 4
)

var SessionType_name = map[int32]string{
	0: "Unknown",
	1: "SignIn",
	2: "Sync",
	3: "Heartbeat",
	4: "MessageStream",
}

var SessionType_value = map[string]int32{
	"Unknown":       0,
	"SignIn":        1,
	"Sync":          2,
	"Heartbeat":     3,
	"MessageStream": 4,
}

func (x SessionType) String() string {
	return proto.EnumName(SessionType_name, int32(x))
}

func (SessionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type MessageType int32

const (
	MessageType_MsgUnknown MessageType = 0
	MessageType_MsgText    MessageType = 1
	MessageType_MsgImage   MessageType = 2
)

var MessageType_name = map[int32]string{
	0: "MsgUnknown",
	1: "MsgText",
	2: "MsgImage",
}

var MessageType_value = map[string]int32{
	"MsgUnknown": 0,
	"MsgText":    1,
	"MsgImage":   2,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

type Output struct {
	Type                 SessionType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.SessionType" json:"type,omitempty"`
	Id                   int64       `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Errcode              int32       `protobuf:"varint,3,opt,name=errcode,proto3" json:"errcode,omitempty"`
	Message              string      `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []byte      `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetType() SessionType {
	if m != nil {
		return m.Type
	}
	return SessionType_Unknown
}

func (m *Output) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Output) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *Output) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Output) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Input struct {
	Type                 SessionType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.SessionType" json:"type,omitempty"`
	RequiredId           int64       `protobuf:"varint,2,opt,name=required_id,json=requiredId,proto3" json:"required_id,omitempty"`
	Data                 []byte      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetType() SessionType {
	if m != nil {
		return m.Type
	}
	return SessionType_Unknown
}

func (m *Input) GetRequiredId() int64 {
	if m != nil {
		return m.RequiredId
	}
	return 0
}

func (m *Input) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Message struct {
	RequestId            int64        `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ReceiverId           int64        `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	ReceiverIds          []int64      `protobuf:"varint,3,rep,packed,name=receiver_ids,json=receiverIds,proto3" json:"receiver_ids,omitempty"`
	MessageType          MessageType  `protobuf:"varint,4,opt,name=messageType,proto3,enum=pb.MessageType" json:"messageType,omitempty"`
	MessageBody          *MessageBody `protobuf:"bytes,5,opt,name=messageBody,proto3" json:"messageBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Message) GetReceiverId() int64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *Message) GetReceiverIds() []int64 {
	if m != nil {
		return m.ReceiverIds
	}
	return nil
}

func (m *Message) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_MsgUnknown
}

func (m *Message) GetMessageBody() *MessageBody {
	if m != nil {
		return m.MessageBody
	}
	return nil
}

type MessageBody struct {
	MessageType          MessageType     `protobuf:"varint,1,opt,name=messageType,proto3,enum=pb.MessageType" json:"messageType,omitempty"`
	MessageContent       *MessageContent `protobuf:"bytes,2,opt,name=messageContent,proto3" json:"messageContent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MessageBody) Reset()         { *m = MessageBody{} }
func (m *MessageBody) String() string { return proto.CompactTextString(m) }
func (*MessageBody) ProtoMessage()    {}
func (*MessageBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *MessageBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageBody.Unmarshal(m, b)
}
func (m *MessageBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageBody.Marshal(b, m, deterministic)
}
func (m *MessageBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageBody.Merge(m, src)
}
func (m *MessageBody) XXX_Size() int {
	return xxx_messageInfo_MessageBody.Size(m)
}
func (m *MessageBody) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageBody.DiscardUnknown(m)
}

var xxx_messageInfo_MessageBody proto.InternalMessageInfo

func (m *MessageBody) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_MsgUnknown
}

func (m *MessageBody) GetMessageContent() *MessageContent {
	if m != nil {
		return m.MessageContent
	}
	return nil
}

type MessageContent struct {
	// Types that are valid to be assigned to Content:
	//	*MessageContent_Text
	//	*MessageContent_Image
	Content              isMessageContent_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MessageContent) Reset()         { *m = MessageContent{} }
func (m *MessageContent) String() string { return proto.CompactTextString(m) }
func (*MessageContent) ProtoMessage()    {}
func (*MessageContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *MessageContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageContent.Unmarshal(m, b)
}
func (m *MessageContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageContent.Marshal(b, m, deterministic)
}
func (m *MessageContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageContent.Merge(m, src)
}
func (m *MessageContent) XXX_Size() int {
	return xxx_messageInfo_MessageContent.Size(m)
}
func (m *MessageContent) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageContent.DiscardUnknown(m)
}

var xxx_messageInfo_MessageContent proto.InternalMessageInfo

type isMessageContent_Content interface {
	isMessageContent_Content()
}

type MessageContent_Text struct {
	Text *Text `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type MessageContent_Image struct {
	Image *Image `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

func (*MessageContent_Text) isMessageContent_Content() {}

func (*MessageContent_Image) isMessageContent_Content() {}

func (m *MessageContent) GetContent() isMessageContent_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *MessageContent) GetText() *Text {
	if x, ok := m.GetContent().(*MessageContent_Text); ok {
		return x.Text
	}
	return nil
}

func (m *MessageContent) GetImage() *Image {
	if x, ok := m.GetContent().(*MessageContent_Image); ok {
		return x.Image
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MessageContent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MessageContent_Text)(nil),
		(*MessageContent_Image)(nil),
	}
}

type Text struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Text) Reset()         { *m = Text{} }
func (m *Text) String() string { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()    {}
func (*Text) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *Text) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Text.Unmarshal(m, b)
}
func (m *Text) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Text.Marshal(b, m, deterministic)
}
func (m *Text) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Text.Merge(m, src)
}
func (m *Text) XXX_Size() int {
	return xxx_messageInfo_Text.Size(m)
}
func (m *Text) XXX_DiscardUnknown() {
	xxx_messageInfo_Text.DiscardUnknown(m)
}

var xxx_messageInfo_Text proto.InternalMessageInfo

func (m *Text) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Image struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Image) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Image) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Image) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.SessionType", SessionType_name, SessionType_value)
	proto.RegisterEnum("pb.MessageType", MessageType_name, MessageType_value)
	proto.RegisterType((*Output)(nil), "pb.Output")
	proto.RegisterType((*Input)(nil), "pb.Input")
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*MessageBody)(nil), "pb.MessageBody")
	proto.RegisterType((*MessageContent)(nil), "pb.MessageContent")
	proto.RegisterType((*Text)(nil), "pb.Text")
	proto.RegisterType((*Image)(nil), "pb.Image")
}

func init() {
	proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd)
}

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x8f, 0xd3, 0x3c,
	0x10, 0xae, 0xf3, 0xd1, 0x36, 0xe3, 0xb6, 0x6f, 0x5e, 0x0b, 0xa1, 0x08, 0x09, 0xc8, 0x86, 0x4b,
	0xb4, 0x87, 0x4a, 0x94, 0x0b, 0xe2, 0xb8, 0x5c, 0x9a, 0x43, 0x84, 0xe4, 0x16, 0x71, 0x03, 0xa5,
	0xb5, 0x95, 0x46, 0x50, 0x27, 0xc4, 0x2e, 0xbb, 0x95, 0xb8, 0xf2, 0x07, 0xf9, 0x45, 0xc8, 0x8e,
	0xdb, 0xa6, 0x7b, 0xda, 0x9b, 0x67, 0xe6, 0xf9, 0x98, 0xb1, 0xc7, 0x30, 0xdd, 0x73, 0x29, 0x8b,
	0x92, 0xcf, 0x9b, 0xb6, 0x56, 0x35, 0x71, 0x9a, 0x4d, 0xf2, 0x07, 0xc1, 0xf0, 0xd3, 0x41, 0x35,
	0x07, 0x45, 0xde, 0x80, 0xa7, 0x8e, 0x0d, 0x8f, 0x50, 0x8c, 0xd2, 0xd9, 0xe2, 0xbf, 0x79, 0xb3,
	0x99, 0xaf, 0xb8, 0x94, 0x55, 0x2d, 0xd6, 0xc7, 0x86, 0x53, 0x53, 0x24, 0x33, 0x70, 0x2a, 0x16,
	0x39, 0x31, 0x4a, 0x5d, 0xea, 0x54, 0x8c, 0x44, 0x30, 0xe2, 0x6d, 0xbb, 0xad, 0x19, 0x8f, 0xdc,
	0x18, 0xa5, 0x3e, 0x3d, 0x85, 0xba, 0x62, 0xed, 0x22, 0x2f, 0x46, 0x69, 0x40, 0x4f, 0x21, 0x21,
	0xe0, 0xb1, 0x42, 0x15, 0x91, 0x1f, 0xa3, 0x74, 0x42, 0xcd, 0x39, 0x29, 0xc0, 0xcf, 0xc4, 0x93,
	0xbb, 0x78, 0x0d, 0xb8, 0xe5, 0x3f, 0x0f, 0x55, 0xcb, 0xd9, 0xb7, 0x73, 0x3b, 0x70, 0x4a, 0x65,
	0xec, 0x6c, 0xe1, 0xf6, 0x2c, 0xfe, 0x22, 0x18, 0xe5, 0xb6, 0x85, 0x97, 0x60, 0xd0, 0x5c, 0x2a,
	0xcd, 0x47, 0x86, 0x1f, 0xd8, 0x4c, 0xc6, 0x3a, 0xfd, 0x2d, 0xaf, 0x7e, 0xf1, 0xf6, 0x4a, 0xbf,
	0x4b, 0x65, 0x8c, 0xdc, 0xc0, 0xa4, 0x07, 0x90, 0x91, 0x1b, 0xbb, 0xa9, 0x4b, 0xf1, 0x05, 0x21,
	0xc9, 0x5b, 0xc0, 0x76, 0x60, 0xdd, 0xb8, 0xb9, 0x03, 0x3b, 0x4f, 0x7e, 0x49, 0xd3, 0x3e, 0xa6,
	0x47, 0xb9, 0xab, 0xd9, 0xd1, 0xdc, 0x0f, 0xbe, 0xa2, 0xe8, 0x34, 0xed, 0x63, 0x92, 0xdf, 0x80,
	0x7b, 0xb5, 0xc7, 0xa6, 0xe8, 0x09, 0xa6, 0x1f, 0x60, 0x66, 0xc3, 0x8f, 0xb5, 0x50, 0x5c, 0x28,
	0x33, 0x2e, 0x5e, 0x90, 0x1e, 0xcb, 0x56, 0xe8, 0x23, 0x64, 0xf2, 0x15, 0x66, 0xd7, 0x08, 0xf2,
	0x0a, 0x3c, 0xc5, 0x1f, 0x94, 0x71, 0xc6, 0x8b, 0xb1, 0xd6, 0x58, 0xf3, 0x07, 0xb5, 0x1c, 0x50,
	0x93, 0x27, 0x37, 0xe0, 0x57, 0x7b, 0xbd, 0x13, 0x9d, 0x49, 0xa0, 0x01, 0x99, 0x4e, 0x2c, 0x07,
	0xb4, 0xab, 0xdc, 0x05, 0x30, 0xda, 0x5a, 0xfd, 0x17, 0xe0, 0x69, 0xb6, 0x7e, 0xce, 0xb3, 0x6a,
	0xd0, 0x29, 0x25, 0x5f, 0xc0, 0x37, 0x44, 0xbb, 0x92, 0x5d, 0x49, 0xaf, 0xe4, 0x33, 0xf0, 0xef,
	0x2b, 0xa6, 0x76, 0xc6, 0xc2, 0xa7, 0x5d, 0x40, 0x9e, 0xc3, 0x70, 0xc7, 0xab, 0x72, 0xa7, 0xec,
	0x9e, 0xda, 0x88, 0x84, 0xe0, 0x1e, 0xda, 0x1f, 0x76, 0x45, 0xf5, 0xf1, 0x96, 0x02, 0xee, 0x6d,
	0x1c, 0xc1, 0x30, 0xfa, 0x2c, 0xbe, 0x8b, 0xfa, 0x5e, 0x84, 0x03, 0x02, 0x30, 0x5c, 0x55, 0xa5,
	0xc8, 0x44, 0x88, 0xc8, 0x18, 0xbc, 0xd5, 0x51, 0x6c, 0x43, 0x87, 0x4c, 0x21, 0x58, 0xf2, 0xa2,
	0x55, 0x1b, 0x5e, 0xa8, 0xd0, 0x25, 0xff, 0xc3, 0xd4, 0xde, 0xca, 0x4a, 0xb5, 0xbc, 0xd8, 0x87,
	0xde, 0xed, 0xfb, 0xf3, 0x33, 0xad, 0xbb, 0x5f, 0x04, 0xb9, 0x2c, 0x2f, 0xb2, 0x18, 0x46, 0xb9,
	0x2c, 0xf5, 0xa8, 0x21, 0x22, 0x13, 0x18, 0xe7, 0xb2, 0x34, 0xb3, 0x85, 0xce, 0x66, 0x68, 0xfe,
	0xea, 0xbb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x82, 0x87, 0x5b, 0x8e, 0xbc, 0x03, 0x00, 0x00,
}
